# Deployment Spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    # This is the pod template
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: phuclmh/udagram-frontend:v1
          imagePullPolicy: Always # Required image pull
          # Secrets of Pod is required
          # If secret does not exist the Pod will fail during startup.
          volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true
          ports:
            - containerPort: 80
          # To define all of the ConfigMap's data as container environment variables.
          # The key from the ConfigMap becomes the environment variable name in the Pod.
          envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secret
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
      restartPolicy: Always
    # The pod template ends here